// Lista simple de destinos turísticos argentinos para el autocompletado del
// campo "Destino". No es exhaustiva ni viene de una API: es una lista fija
// pensada para la demo, sin agregar una dependencia externa de geocoding.
export const ARGENTINA_DESTINATIONS = [
  "Buenos Aires",
  "Mar del Plata",
  "Villa Gesell",
  "Pinamar",
  "Tandil",
  "Bariloche",
  "Villa La Angostura",
  "San Martín de los Andes",
  "El Calafate",
  "El Chaltén",
  "Ushuaia",
  "Puerto Madryn",
  "Comodoro Rivadavia",
  "Mendoza",
  "San Rafael",
  "Córdoba",
  "Villa Carlos Paz",
  "La Cumbrecita",
  "Salta",
  "Cafayate",
  "Jujuy",
  "Tafí del Valle",
  "Tucumán",
  "Rosario",
  "Santa Fe",
  "Paraná",
  "Puerto Iguazú",
  "Posadas",
  "Corrientes",
  "Neuquén",
  "San Juan",
  "San Luis",
  "Merlo",
  "La Rioja",
  "Catamarca",
  "Santiago del Estero",
  "La Plata",
  "Tigre",
];
